type calcButton = {
    id: number,
    text: string,
    size: number,
}

export const calcButtons = [
    {
        key: 'numKey1',
        id: 0,
        type: 'num',
        text: '1',
        size: 1,
    },
    {
        key: 'numKey2',
        id: 1,
        type: 'num',
        text: '2',
        size: 1,
    },
    {
        key: 'numKey3',
        id: 2,
        type: 'num',
        text: '3',
        size: 1,
    },
    {
        key: 'plusKey',
        id: 3,
        type: 'basicOp',
        text: '+',
        size: 1,
    },
    {
        key: 'numKey4',
        id: 4,
        type: 'num',
        text: '4',
        size: 1,
    },
    {
        key: 'numKey5',
        id: 5,
        type: 'num',
        text: '5',
        size: 1,
    },
    {
        key: 'numKey6',
        id: 6,
        type: 'num',
        text: '6',
        size: 1,
    },
    {
        key: 'minusKey',
        id: 7,
        type: 'basicOp',
        text: '-',
        size: 1,
    },
    {
        key: 'numKey7',
        id: 8,
        type: 'num',
        text: '7',
        size: 1,
    },
    {
        key: 'numKey8',
        id: 9,
        type: 'num',
        text: '8',
        size: 1,
    },
    {
        key: 'numKey9',
        id: 10,
        type: 'num',
        text: '9',
        size: 1,
    },
    {
        key: 'divideKey',
        id: 11,
        type: 'basicOp',
        text: '/',
        size: 1,
    },
    {
        key: 'openParenthesesKey',
        id: 12,
        type: 'symbols',
        text: '(',
        size: 1,
    },
    {
        key: 'closeParenthesesKey',
        id: 13,
        type: 'symbols',
        text: ')',
        size: 1,
    },
    {
        key: 'numKey0',
        id: 14,
        type: 'num',
        text: '0',
        size: 1,
    },
    {
        key: 'multiplyKey',
        id: 15,
        type: 'basicOp',
        text: '*',
        size: 1,
    },
    {
        key: 'equalsKey',
        id: 16,
        type: 'basicOp',
        text: '=',
        size: 2,
    },
    {
        key: 'clearKey',
        id: 17,
        type: 'basicOp',
        text: 'clr',
        size: 1,
    }
]